### ISSUE TITLE
[Feature Request] macOS server support?

### ISSUE THREAD

**Issue by GreatHaop** [BeamMP/BeamMP-Server#107]
**Is your feature request related to a problem? Please describe.**
Although BeamMP server does run on parallels desktop on mac, I want a native version
**Describe the solution you'd like**
Add macOS support
**Describe alternatives you've considered**

**Additional context**

**Comment by lionkor** [comment]
Hello, thanks for your suggestion! I've moved it to the correct place :)

We had macos support for a bit, by building it yourself. You can still do this, but it requires CMake knowledge.

If there's enough demand for this, I'd be happy to make that work. If you can find someone who has MacOS and knows CMake and C++, you could get them to PR a change that makes this work.

**Comment by lionkor** [comment]
Fixed in #110, please reopen if the issue persists nonetheless.
