### ISSUE TITLE
[Bug] Building

### ISSUE THREAD

**Issue by QuintenQVD0** [BeamMP/BeamMP-Server#111]
**Fill out general information**
OS  linux debian 10 buster 
BeamMP-Server Version: V3.0.1

**Describe the bug**
I get a error when building in a docker container (Docker base image is debian:buster-slim)

**To Reproduce**

1. run the install script I made: https://pastebin.com/vuRF8Dkv
2. install logs: https://pteropaste.com/avqfr9/
3. error 
```
 77%] [32mBuilding CXX object CMakeFiles/BeamMP-Server.dir/src/Compat.cpp.o[0m
[ 78%] [32mBuilding CXX object CMakeFiles/BeamMP-Server.dir/src/Common.cpp.o[0m
[01m[K/mnt/server/BeamMP-Server/src/Common.cpp:[m[K In function '[01m[Kvoid RegisterThread(const string&)[m[K':
[01m[K/mnt/server/BeamMP-Server/src/Common.cpp:154:31:[m[K [01;31m[Kerror: [m[K'[01m[Kgettid[m[K' was not declared in this scope
     ThreadId = std::to_string([01;31m[Kgettid[m[K());
                               [01;31m[K^~~~~~[m[K
[01m[K/mnt/server/BeamMP-Server/src/Common.cpp:154:31:[m[K [01;36m[Knote: [m[Ksuggested alternative: '[01m[Kgetgid[m[K'
     ThreadId = std::to_string([01;36m[Kgettid[m[K());
                               [01;36m[K^~~~~~[m[K
                               [32m[Kgetgid[m[K
make[2]: *** [CMakeFiles/BeamMP-Server.dir/build.make:115: CMakeFiles/BeamMP-Server.dir/src/Common.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/BeamMP-Server.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
**Expected behavior**
This should build to a executable

**Logs**
Not because it is not builded yet

**Comment by lionkor** [comment]
Yeah, that should build, that looks like an incompatibility in the debian kernel.

For now, the hotfix would be to go into src/Common.cpp:154 and simply remove the line.

**Comment by lionkor** [comment]
The real fix here would be to remove that entire thread logging code in release builds. I added it to the 3.0.2 milestone.

Thanks for reporting :)

**Comment by QuintenQVD0** [comment]
Note, If I use debian 11 to build , It builds fine. I got It working on ARM64
