### ISSUE TITLE
[Bug] Building does not work anymore after v3.0.2 was released

### ISSUE THREAD

**Issue by QuintenQVD0** [BeamMP/BeamMP-Server#112]
**Fill out general information**
OS debian 11
BeamMP-Server Version: v3.0.1 or v3.0.2

**Describe the bug**
I can't get v3.0.1 or v3.0. 2 not to build

**To Reproduce**
1. install script: https://pastebin.com/cLy7NmHy
2. run this install script

**Expected behavior**
I should be able to build v3.0.1 or v3.0.2 

**Logs**
 Install logs v3.0.1 = https://pteropaste.com/ypr9hd
 Install logs v3.0.2 = https://pteropaste.com/mlgjr3/

**Additional context**
I got 2 days ago with the exact same script v3.0.1 to build after changing to debian 11: https://github.com/BeamMP/BeamMP-Server/issues/111 now it does not work anymore

**Comment by lionkor** [comment]
Hi! Can you try switching these lines around please:
```sh
git submodule update --init --recursive
git checkout tags/${VERSION}
```
It should checkout, then submodule update :)

**Comment by QuintenQVD0** [comment]
> Hi! Can you try switching these lines around please:
> 
> ```shell
> git submodule update --init --recursive
> git checkout tags/${VERSION}
> ```
> 
> It should checkout, then submodule update :)

new install script: https://pastebin.com/TbkMzeNH

v3.0.2 = https://pteropaste.com/rawz0p ( container just goos from cpu 100% to 5% and it is not killed, It just does not go furder)
v3.0.1= https://pteropaste.com/m02j7q ( container just goos from cpu 100% to 5% and it is not killed, It just does not go furder )

It does not work

**Comment by lionkor** [comment]
That's a container issue of some kind, the build isn't failing as far as I can tell

**Comment by QuintenQVD0** [comment]
On my debian 11 vm 3 gb I have the same issue

**Comment by QuintenQVD0** [comment]
nevermind, It builds on my vm if I use the right branch rc-v3.0.2 (AMD64) but in docker on my ARM64 VM with the right branch it fails (docker)

**Comment by QuintenQVD0** [comment]
Is there any fix that can be done to this? I would like to run (and compile)  it on ARM64. Yestrday about 24h ago it worked fine

**Comment by lionkor** [comment]
I'm not quite sure what the issue is - is it possibly running out of RAM?

**Comment by QuintenQVD0** [comment]
> I'm not quite sure what the issue is - is it possibly running out of RAM?

Yea I think that was hapening, I gave the install container some more ram and with some bash and git magic I got it to work for v3.0.2 and v3.0.1 on ARM64

**Comment by lionkor** [comment]
Glad to hear that! Sadly RAM usage during build is not something we can do much about. You could, in the future, try to give the container swap (if thats a thing, im not sure right now), to prevent this in the future without allocating crazy RAM to the container!

**Comment by QuintenQVD0** [comment]
> Glad to hear that! Sadly RAM usage during build is not something we can do much about. You could, in the future, try to give the container swap (if thats a thing, im not sure right now), to prevent this in the future without allocating crazy RAM to the container!

The default in ptero for the install container is 1024MB so 1Gb and 1 thread. I changed it to 2GB ram and 125% cpu so that is 1.25 thread. and it builded fine for ARM64. Thanks for the support!

**Comment by lionkor** [comment]
By the way, your script sets the map to `gridmap`, which won't work. It needs to be `gridmap_v2` (`/levels/gridmap_v2/info.json`) instead. We're not sure which egg does this, but someone started it, and now it's everywhere.

**Comment by QuintenQVD0** [comment]
> gridmap_v2



> By the way, your script sets the map to `gridmap`, which won't work. It needs to be `gridmap_v2` (`/levels/gridmap_v2/info.json`) instead. We're not sure which egg does this, but someone started it, and now it's everywhere.

haha, Thx I changed that now every server that is made with my egg (special made for arm64) now set the map to /levels/gridmap_v2/info.json
