### ISSUE TITLE
[Bug] Server does not compile on alpine linux

### ISSUE THREAD

**Issue by RouHim** [BeamMP/BeamMP-Server#117]
**Fill out general information**
OS: alpine
BeamMP-Server Version: master / 3.0.2

**Describe the bug**
The server compile fails with the following error message on alpine linux docker build:
https://github.com/RouHim/beammp-docker/runs/7515428495?check_suite_focus=true

**To Reproduce**
1. Checkout: `git clone https://github.com/RouHim/beammp-docker`
2. Checkout the unfixed state: `git checkout 1ebf564e1f872fda1287f20b6502b9a29c9bde30`
3. Run `docker build -t rouhim/beammp-server . `

**Expected behavior**
Should build

**Logs**
See: https://github.com/RouHim/beammp-docker/runs/7515428495?check_suite_focus=true

**Additional context**
Works for 3.0.1

**Comment by RouHim** [comment]
@lionkor Can I help smh to get this fixed?

**Comment by lionkor** [comment]
Sorry, currently on break. Will look at it when I'm back.

**Comment by lionkor** [comment]
Either that should fix it, or only building the server (in case you're (as per default)) also building the tests.

**Comment by RouHim** [comment]
Ty, I'll test it.

**Comment by RouHim** [comment]
> Either that should fix it, or only building the server (in case you're (as per default)) also building the tests.

How can I disable the tests? With the flag: `BUILD_TESTS=OFF`?

Edit:
Ok nice, that actually worked :D 
Looking forward for this PR.

**Comment by RouHim** [comment]
For completeness I would like to mention that a build under ARMv7 does not work:
https://github.com/RouHim/beammp-container-image/actions/runs/3205137915/jobs/5237287004

**Comment by RouHim** [comment]
The latest release version works again. Thanks.

**Comment by lionkor** [comment]
I'm very glad!
