### ISSUE TITLE
[Bug] UDP - the cause of most of the Desync

### ISSUE THREAD

**Issue by OfficialLambdax** [BeamMP/BeamMP-Server#120]
**Fill out general information**
OS (windows, linux, ...): All
BeamMP-Server Version: All

**Describe the bug**
I dont have to explain how UDP works. But you know how if two packets are send
eg.
Packet 1 at, lets say 00:01 (MM:SS)
Packet 2 at, lets say 00:02

then it can happen that packet 2 arrives before packet 1.
Now if that happens with positional updates then that causes desync if the software doesnt reject already outdated data, aka packet 1.

The hereby important packet that causes the car to be moved is the Zp packet
Zp:2-0:{"rot":[...],"rvel":[...],"tim":1164.3065292053,"vel":[...],"pos":[...],"ping":...}

And in it is exactly what we need to resolve that problem. the "tim" value. It contains the SS.MS since when the car has been spawned. If the server remembers that value and then checks on each new Zp packet

if "oldtim" > "newtim" then
  reject packet
else
  remember "newtime"
  broadcast packet
endif

the problem would be resolved and players with lots of ping spikes or a high ping in general would be less of a cause for desync.

I think this should be done within the server, instead of the game client, to spare unnecessary bandwith. Not that beammp takes any considerable at all, but yk efficiency and all.

**Comment by lionkor** [comment]
> Not that beammp takes any considerable at all

BeamMP takes *massive* bandwidth at the moment. Its multiple TB per month for larger communities with multiple servers. Just wanted to point that out ;)

Yes this needs to be fixed.

**Comment by OfficialLambdax** [comment]
This is plagueing players every day, when will it be adressed

**Comment by snepsnepsnep** [comment]
It has been addressed client side for now.

**Comment by OfficialLambdax** [comment]
This is great news. It should fix the forth and back warping of vehicles for now. Is this fix already delivered within 4.4.3?
