### ISSUE TITLE
[Bug] No error in console

### ISSUE THREAD

**Issue by ghost** [BeamMP/BeamMP-Server#124]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Beammp server console sometimes does not show errors

**To Reproduce**
Have a table for each player indexed by name. 

Purposely nil out that entry

Then try to access the data/table 

Instead of saying something along the lines of "attempt to index nil value" it will just say nothing in the console, when it used to. This is with no other errors in the console.

**Expected behavior**
Print out LUA error in console when trying to index a nil value etc 

**Desktop (please complete the following information):**
 - OS + Version: [Windows Server 2019]

**Comment by lionkor** [comment]
Which server version?

**Comment by ghost** [comment]
> Which server version? 

3.0.2

**Comment by lionkor** [comment]
3.1.0 (not released yet) should fix this, I will send you a version later today to try out, okay?

**Comment by ghost** [comment]
> 3.1.0 (not released yet) should fix this, I will send you a version later today to try out, okay?

Oh wow okay thanks a lot! So this was something that you have found a fix for already or just now? Just curious

**Comment by lionkor** [comment]
found another place where this was happening, so this is all now fixed with #83 once merged
