### ISSUE TITLE
[Bug] Pass player username and identifiers on `onPlayerDisconnect` event

### ISSUE THREAD

**Issue by Mack29446** [BeamMP/BeamMP-Server#135]
**Is your feature request related to a problem? Please describe.**
Often, when the `onPlayerDisconnect` event is triggered, the player has already been removed from the `MP.GetPlayerIdentifiers()` and `MP.GetPlayerName()` tables, which makes it difficult to keep track of players.

**Describe the solution you'd like**
Two additional variables on the `onPlayerDisconnect` event

**Describe alternatives you've considered**
Only remove the player from the `MP.GetPlayerIdentifiers()` and `MP.GetPlayerName()` tables after the event has been returned.

**Comment by daniel-w0** [comment]
Good idea, I'll check it out soon.
My workaround in Lua is to add the users to a table when they join.

**Comment by lionkor** [comment]
I looked into it - this was a bug, and will be fixed in v3.1.1 (#142)
