### ISSUE TITLE
Starting a server on debian11

### ISSUE THREAD

**Issue by QuintenQVD0** [BeamMP/BeamMP-Server#144]
Hi there,

I am updatig my pterodactyl egg to support the latest update v3.1.0 but it needs libssl3 to run and that package is not avaible on debian 11 but only on 12 what is not yet realeased and we use docker to run the servers it is not realy posible to install this package with our current setup and it needs it to start. https://github.com/parkervcp/eggs/issues/1930 Is there any way we can fix this as we mostly use debian for our game containers?

**Comment by Mack29446** [comment]
There is an official Debian build on the 3.1.0 release: https://github.com/BeamMP/BeamMP-Server/releases/tag/v3.1.0

**Comment by QuintenQVD0** [comment]
> There is an official Debian build on the 3.1.0 release: https://github.com/BeamMP/BeamMP-Server/releases/tag/v3.1.0

Thank you did not see that
