### ISSUE TITLE
[Feature Request] Add `version` console command to display the server version

### ISSUE THREAD

**Issue by Mack29446** [BeamMP/BeamMP-Server#148]
**Is your feature request related to a problem? Please describe.**
It would make it easier to maintain and update the server if I could easily check the version with a command. Software like Pterodactyl may not allow you to scroll up far in the console

**Describe the solution you'd like**
a `version` command in the server console

**Describe alternatives you've considered**
Displaying the version number in the `status` command

**Comment by lionkor** [comment]
We do already have `./BeamMP-Server --version`, for your information.
A `version` command sounds really good to have, though, thank you

**Comment by lionkor** [comment]
Oh, there's also `print(MP.GetServerVersion())` in the Lua console (`lua`), if you need to do it on servers before we add this :^)
