### ISSUE TITLE
Update docs for debian boost library

### ISSUE THREAD

**Issue by synth80s** [BeamMP/BeamMP-Server#15]
Debian is listed as the supported OS, not ubuntu. In ubuntu it’s really easy to add a ppa but in Debian 10 I could not get it to work. Also ubuntu PPAs are not supposed to be supported or used in Debian. I ended up downloading boost 1.70 from source forge and compiling it. Maybe want to add a note about that.

**Comment by PacketShepard** [comment]
You can do this on Debian to get an official libboost 1.7x version

```
printf "deb http://deb.debian.org/debian buster-backports main\n" > /etc/apt/sources.list.d/buster-backports.list
apt-get update && apt-get install -y libboost1.74-all-dev
OR
apt-get update && apt-get install -y libboost1.71-all-dev
```

**Comment by lionkor** [comment]
Adding to say that we encourage to build boost from source. You will need boost-system, boost-thread and probably boost-headers.

I use this script currently in one of the automated builds:

```sh
wget https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.gz
tar xzf boost_1_75_0.tar.gz
cd boost_1_75_0
./bootstrap.sh
./b2 toolset=gcc --with-system --with-thread # maybe add --with-headers, --build-dir=..., install, stage, ...
```

**Comment by lionkor** [comment]
You no longer need boost to run the server, only to compile it. I'll consider this closed since we distribute binaries that should work on debian and ubuntu.
