### ISSUE TITLE
[Bug] FreeBSD Support

### ISSUE THREAD

**Issue by jamieahelmke** [BeamMP/BeamMP-Server#160]
**Fill out general information**
OS:
`FreeBSD 13.1-RELEASE`
BeamMP-Server Version:
`Latest Release (v3.1.1)` 

**Describe the bug**
Unfortunately, the software does not compile on FreeBSD. I have tried installing all the build dependencies that are installed on Ubuntu according to the guide. 

**To Reproduce**
1. I installed following dependencies:
```
git
boost-libs
pthreadpool
cmake
curl
openssl
tolua
lua53
gcc
websocketpp
lzlib
zlib-ng
```

2. Run `cmake . -DCMAKE_BUILD_TYPE=Release` like in the Docs

3. Run `make`

**Expected behavior**
Clean Compile, additionally add FreeBSD Dependencies

**Logs**
No missing library errors anymore, but errors like "Unsupported platform"

**Comment by jimkoen** [comment]
@lionkor I'm claiming this issue

**Comment by jamieahelmke** [comment]
@jimkoen Note: meanwhile FreeBSD 14.0 is the newest stable release.
https://www.freebsd.org/where/
