### ISSUE TITLE
[Bug] Client Freeze sometimes results in server freeze/event queue back up

### ISSUE THREAD

**Issue by ghost** [BeamMP/BeamMP-Server#168]
**Fill out general information**
OS (windows, linux, ...):
BeamMP-Server Version:
Latest Version/3.1.1 Ubuntu 20.04
**Describe the bug**
Sometimes when a client's computer freezes, it will cause the events in the server to queue up until either:
1) the clients PC stops freezing and disconnects, doesn't always work
2)The client sometimes may also fix the server by rejoining but this always doesn't work either.

**To Reproduce**
Not 100% how to replicate everytime, seems to only happen if you have a lot of events in the server?
To get it to happen sometimes I:
1) Get into my server with at least a few others in and tab to another program or intentionally freeze my game
2) watch the console as all events start queuing up 

**Expected behavior**
Should be able to have a client game freeze without breaking the server.
**Logs**
Please attach the `Server.log` from the run in which the issue appeared, preferably with Debug turned on in the `ServerConfig.toml`.

**Additional context**
Originally thought this issue was caused by a client side timer that sends info to server once per sec but this persists after removing that.

**Comment by lionkor** [comment]
If you do timing, please do it server-side - event timers don't let the queue back up. Can you please go into the lua (via `lua plugin-name`, like `lua CnR`) when it's backing up, and tell it `:queued`? It will tell you how many (and which) events are queued up.

**Comment by ghost** [comment]
Yes like i stated in the issue, I not longer do timers that way but the issue still persists. Only consistent Client->server communication i make is sending fuel number like every 30 seconds so i don't see that being the cause.

I can try that, however when this happens not even console commands will work IIRC.

I know this for a fact with the MP commands in console but ill try to do the queue command next time didn't know about that thank you!
