### ISSUE TITLE
SIGILL on static v2.0.3 linux release

### ISSUE THREAD

**Issue by Ae3NerdGod** [BeamMP/BeamMP-Server#17]
static build of 2.0.3 not working for me, clean ubuntu 20.04 or after installing dependencies (just tried it i know it shouldnt affect a static build)
its on a first gen i3 if that makes any difference (different set of instruction sets than build env or something?)
here is error from terminal:
`scripts/runBeamMP.sh: line 4:  2099 Illegal instruction     (core dumped) ./BeamMP-Server`

regular linux build works correctly.

**Comment by lionkor** [comment]
Hello! Sorry for the late reply! 

This is definitely my fault, this static executable in the v2.0.3 release was very experimental, works on some systems, doesn't work on others. I'll put out a fixed version here soon, would you be down to test it with me? 

This crash is very tricky to track down, but I believe I know what caused it. 

Could you post your `lscpu` output, as well as `lsb_release -a` and `uname -a`? Those or any subset of those would help me greatly to reproduce the issue! 

Thank you very much and sorry for the inconvenience!

**Comment by blackbyrd84** [comment]
I am receiving the same issue, attached are the requested bits of information. Let me know if you need anything else.
[lscpu.txt](https://github.com/BeamMP/BeamMP-Server/files/6288444/lscpu.txt)
[uname.txt](https://github.com/BeamMP/BeamMP-Server/files/6288445/uname.txt)
[lsb_release.txt](https://github.com/BeamMP/BeamMP-Server/files/6288446/lsb_release.txt)

**Comment by lionkor** [comment]
@blackbyrd84 please also add `ldd --version`, if you can! Thanks for the help!

**Comment by blackbyrd84** [comment]
Ope, my apologies, I missed the edit. Here you go!
[ldd.txt](https://github.com/BeamMP/BeamMP-Server/files/6288459/ldd.txt)

**Comment by Anonymous-275** [comment]
Works for me
[lscpu.txt](https://github.com/BeamMP/BeamMP-Server/files/6288453/lscpu.txt)
[ldd.txt](https://github.com/BeamMP/BeamMP-Server/files/6288457/ldd.txt)
[uname.txt](https://github.com/BeamMP/BeamMP-Server/files/6288460/uname.txt)
[lsb.txt](https://github.com/BeamMP/BeamMP-Server/files/6288462/lsb.txt)

**Comment by Ae3NerdGod** [comment]
not working, i3

[uname.txt](https://github.com/BeamMP/BeamMP-Server/files/6288491/uname.txt)
[ldd_vers.txt](https://github.com/BeamMP/BeamMP-Server/files/6288492/ldd_vers.txt)
[lsb_release.txt](https://github.com/BeamMP/BeamMP-Server/files/6288493/lsb_release.txt)
[lscpu.txt](https://github.com/BeamMP/BeamMP-Server/files/6288494/lscpu.txt)

**Comment by lionkor** [comment]
Okay, the issue is that we call getaddrinfo, dlopen, and other library code that is different in basically every single libc version. This means that no matter what we do (for now) this is going to be an issue. For now I was able to remove the boost dependency from the BeamMP-Server, which means you don't need boost to **run** the server anymore. 

This is going to make it easy as you now only need things basically any distro has to run the executables. You'll still need boost to build the server yourself. For now, I'll attach a dynamic ubuntu executable here.
[BeamMP-Server-linux.zip](https://github.com/BeamMP/BeamMP-Server/files/6288728/BeamMP-Server-linux.zip)

Sadly, for now, I can't really fix the static build issue. It will work for sure on arch and any arch-derivatives, and I'll continue working on making it work for all the others, but linux in general likes dynamic executables better.

For anyone interested in helping to fix this, the main issue is the libc version.

**Comment by Ae3NerdGod** [comment]
> but linux in general likes dynamic executables better.

Perhaps an .appimage would be mire suitable?
Dynamic is working fine fwiw.

**Comment by lionkor** [comment]
AppImage is a possibility, yeah :)

**Comment by KickingAnimal** [comment]
> 
> Sadly, for now, I can't really fix the static build issue. It will work for sure on arch and any arch-derivatives, and I'll continue working on making it work for all the others, but linux in general likes dynamic executables better.
>

The static should work on arch? Because it does not work on my arch installation. It prints out something like illeagal  operation and then quits. Let me check in a bit what exactly, as I am away from my server now.

**Comment by lionkor** [comment]
It *should* work on *some* arch, basically random. Sorry about that.

**Comment by lionkor** [comment]
I thought the static build might work, but it's some shitty ABI incompatibility, not much we can do there :(

**Comment by KickingAnimal** [comment]
Oh yeah, well maybe some future version will work, thanks for thinking about us Linux users and trying. for now it's back to running it semi "reliable" under wine🍷

**Comment by lionkor** [comment]
@KickingAnimal You can built it from source with zero issues on any arch, manjaro, debian, ubuntu, alpine (those are the ones I tested).
You don't have to run the wine one on linux for many months now.

**Comment by lionkor** [comment]
The entire server dev team is on linux and we play and run our stuff on linux. Feel free to open a new issue if you encounter problems following the building guide in the readme.

**Comment by Anonymous-275** [comment]
Add to the list of distros that does build the server with no issues: RasbianOS, Fedora, CentOS. All tested by me as well :D

**Comment by Ae3NerdGod** [comment]
> Add to the list of distros that does build the server with no issues: RasbianOS, Fedora, CentOS. All tested by me as well :D

You built on raspberry pi os?  on Arm?

**Comment by Anonymous-275** [comment]
> > Add to the list of distros that does build the server with no issues: RasbianOS, Fedora, CentOS. All tested by me as well :D
> 
> You built on raspberry pi os? on Arm?

yup, it just doesn't work on big-endian currently, but it works on any little-endian CPU.

**Comment by lionkor** [comment]
We will not be able to provide a fully static build. We might do an AppImage sometime. Anyone familiar with AppImage can feel free to PR it.
