### ISSUE TITLE
Add more detailed information to health endpoint

### ISSUE THREAD

**Issue by ghost** [BeamMP/BeamMP-Server#174]
https://github.com/BeamMP/BeamMP-Server/blob/879b9772f5138e8e26b394d2369a1ef8be2a2435/src/Http.cpp#L164-L190

Currently, the health endpoint of the BeamMP server software only returns a boolean value indicating whether all subsystems are good or not. However, it would be helpful to have more detailed information about the status of each subsystem.

Modify the health endpoint to return a JSON object containing the status of each subsystem. For example:

```json
{
    "subsystem1": "good",
    "subsystem2": "starting",
    "subsystem3": "bad"
}
```

This would provide more insight into the health of the server and help with monitoring and troubleshooting.

**Comment by lionkor** [comment]
Planned, please add this to https://github.com/BeamMP/BeamMP-Server/issues/69 instead

**Comment by lionkor** [comment]
Current draft: https://github.com/BeamMP/BeamMP-Server/blob/feature-9/openapi.yml
