### ISSUE TITLE
Remove unused "magic" endpoint from HTTP server

### ISSUE THREAD

**Issue by ghost** [BeamMP/BeamMP-Server#175]
https://github.com/BeamMP/BeamMP-Server/blob/879b9772f5138e8e26b394d2369a1ef8be2a2435/src/Http.cpp#L191-L194

The software has a "magic" endpoint that serves a hardcoded string of characters. This endpoint appears to serve no practical purpose and is not used by any part of the software. As a result, it is unnecessary and should be removed from the codebase to simplify the software.

**Comment by lionkor** [comment]
Its an easteregg, sorry for the confusion
