### ISSUE TITLE
Modify TriggerClientEventJson to support Lua tables directly.

### ISSUE THREAD

**Issue by ghost** [BeamMP/BeamMP-Server#176]
https://github.com/BeamMP/BeamMP-Server/blob/879b9772f5138e8e26b394d2369a1ef8be2a2435/src/LuaAPI.cpp#L116-L135

The `TriggerClientEventJson` function in BeamMP-Server takes a Lua table, converts it to a JSON string using the JsonEncode function, and then sends it to the client. This is an unnecessary step, as Lua tables can be serialized to JSON without the need for a separate encoding function.

Modifying `TriggerClientEventJson` to accept Lua tables directly as input would simplify the code and reduce the number of function calls required to send data to clients. Additionally, this change would make the interface more consistent with other Lua functions that accept Lua tables as input.

To make this change, we can modify `TriggerClientEventJson` to accept a `sol::table` directly, instead of a JSON-encoded string. The function can then serialize the table to JSON internally using `nlohmann::json::dump` and send it to the client.

This change should have no impact on existing functionality, as the function will still accept JSON-encoded strings.

**Comment by lionkor** [comment]
You seem to be confused here.

> Lua tables can be serialized to JSON without the need for a separate encoding function

No, they can't. 

> modify TriggerClientEventJson to accept a sol::table

It literally accepts a sol::table...?! 

Please make sure you understand the code before making suggestions.
