### ISSUE TITLE
[Bug] More detailed explanation of Player connection issues as requested

### ISSUE THREAD

**Issue by ghost** [BeamMP/BeamMP-Server#179]
BeamMP-Server Version:
Latest/ 3.2.0
**Describe the bug**
Players leaving a server can cause one of the following issues:

1) Server does not remove player properly, resulting in the server thinking the player is still there. This also causes the players vehicle to sometimes remain on the other players games. Attempting to drop this player using any method will result in the server Lua state freezing, and no events will be handled (this can sometimes happen immediately after the player leaves, instantly freezing the Lua state without trying to drop them etc). This is only fixed by the player rejoining or restarting the server. 

2) Players with a spotty connection will sometimes seemingly leave the server for a split second, and then immediately rejoin. Upon rejoining, the server will sometimes start spamming a message about a client attempting to send UDP data for another client ID in the console. (Will update this with the proper message when I can find the log for this issue again as it is rare.)

**To Reproduce**
Cannot reliably reproduce the error, however seems to be caused by the following:

1) Exiting out of the game by hitting the "X" on game window or ALT-F4
2) Tabbing to other applications while playing in a server, resulting in the game freezing or crashing(I have witnessed this personally when my game froze and I had the server console up. Fixed when I rejoined.)
3) Players with a spotty connection/high ping seem to cause this more than others.

**Expected behavior**
Players to be able to exit the game and not break everything

**Logs**
Please attach the `Server.log` from the run in which the issue appeared, preferably with Debug turned on in the `ServerConfig.toml`.
Will add when i find the time
**Additional context**

**Comment by Starystars67** [comment]
@Anonymous-275 Please can you reference this issue around the build you are working on going forward for records sake.

**Comment by Starystars67** [comment]
@Anonymous-275 can this issue now be closed as resolved?
If so please tag the commit that fixes & release if it has been done yet?

**Comment by Anonymous-275** [comment]
Sorry didn't get email notifications for some reason, yes it can be 1 sec

**Comment by Anonymous-275** [comment]
[this commit](https://github.com/BeamMP/BeamMP-Server/commit/57a58b1a380ccf2f69805be2365367c1bc8ad99f) fixes this issue
