### ISSUE TITLE
Arch Linux: Which packages do I need to build the server?

### ISSUE THREAD

**Issue by KickingAnimal** [BeamMP/BeamMP-Server#18]
I cannot find the right libraries and other dependencies needed to build from source for my archlinux installation as all the package names in the readme file are Debian/Ubuntu style. Any help in pointing me to the right dependencies for arch would be highly appreciated that's the only unclear part of the build guide

**Comment by lionkor** [comment]
Hi!

On arch and archlinux derivatives, you can use `pacman -Ss NAME` to search for a package, for example `pacman -Ss lua 5.3`.

I think on arch (which I'm on as well) the dependencies are:

- `git`
- `cmake`
- `make`
- `gcc`
- `lua53`
- `zlib`
- `rapidjson`
- `openssl`
- `boost` and `boost-libs`

Command for archlinux to install / update all of those (run as root / sudo):

```sh
pacman -S git cmake make gcc lua53 zlib rapidjson openssl boost boost-libs
```

**Comment by lionkor** [comment]
If you encounter any other issues or if this solved your issue, please reply back :) Good luck!

**Comment by KickingAnimal** [comment]
Yes thanks for the quick response, will test these packages tomorrow (thanks for explaining pacman but know how it works, not my first day on arch ;) ) most of them I did find but I guess I may have missed  boost or boost-libs. Anyway thank you again

**Comment by lionkor** [comment]
Good luck :) 

If you still have issues after, consider joining our [discord](https://discord.gg/beammp) and write me there :) `Lion#5934`

I'll gladly send you an arch binary.

**Comment by KickingAnimal** [comment]
Yes I am in the discord already, was needed before backend update. `KickingAnimal#3556` would gladly take a binary but will still build myself after so I can update/rebuild if needed

**Comment by RichardDastardly** [comment]
Needs boost-libs *and* boost, that caught me out initially - also seems to absolutely need lua53, build failed with the lua51 that was on my build machine. PKGBUILD gratefully accepted sometime :) ( or maybe it can end up in AUR  one day ). I know my way around linux but never actually got round to learning to write PKGBUILDs.

Incidentally the prebuilt ubuntu bin works fine on arch if you manually symlink one of the libraries, I forget which one off the top of my head.

**Comment by lionkor** [comment]
I believe this is solved. Closing for now, reopen if still unclear.
