### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by MrBenboy** [BeamMP/BeamMP-Server#183]
**Is your feature request related to a problem? Please describe.**
While trying to make scripts I noticed that the chat was working synchronously, this is a problem when you want to perform actions when a player writes something in the chat, the message will be sent once all the actions that the 'we want to perform its end.

**Describe the solution you'd like**
There were several solutions to solve this problem, to pass the whole operation of the chat in asyncrone, so that the message is sent directly and that the actions which must be carried out can be carried out in parallel. Another solution would be to make that when we register or trigger an event we can choose whether we do it synchronously or asynchronously (knowing that for the moment the triggerglobalevent does not return the arguments between the plugins)

**Describe alternatives you've considered**
explaine above

**Additional context**
trying to make a script that uses commands in the chat and performs several actions afterwards I noticed that I was blocked because the chat is completely paused as long as the events of the previous command are not finished, so it is for example impossible to make a command that stops the previous one, because the stop command will be carried out once all the actions of the previous command are finished

**Comment by lionkor** [comment]
@MrBenboy please set a title

**Comment by lionkor** [comment]
Missing information after 2 weeks, closing. Reopen once you find the time please
