### ISSUE TITLE
[Feature Request] Environment settings

### ISSUE THREAD

**Issue by pTinosq** [BeamMP/BeamMP-Server#189]
I am hosting a beamng server and would love to do some server-wide night drives. Could we have this functionality please?

**Comment by O1LER** [comment]
Get yourserf https://github.com/prestonelam2003/CobaltEssentials and https://github.com/StanleyDudek/CobaltEssentialsInterface

Im not sure if the base CE can do it already, but managing weather and time of day trough CEI is very nice.

Maybe the CE competitor Nickel can do it too https://github.com/boubouleuh/Nickel-Interface

**Comment by Starystars67** [comment]
I am closing this issue as it is resolved using the scripting interface.
