### ISSUE TITLE
[Feature Request] Add support for Proxy Protocol v2

### ISSUE THREAD

**Issue by Showdown76py** [BeamMP/BeamMP-Server#190]
**Is your feature request related to a problem? Please describe.**
This issue is related to a problem: if a server is working is behind a proxy that is using proxy protocol v2, it will not work and the connection to the socket will be refused. Proxy Protocol v2 proxies allows the server to see the IP from the client.

**Describe the solution you'd like**
An option to toggle in the configuration file, that enables proxy protocol v2 support.

**Comment by lionkor** [comment]
Please feel free to add more information, but as far as I can tell this is not something we can or should implement directly in the server.
