### ISSUE TITLE
[Feature Request] Support of linux/arm64

### ISSUE THREAD

**Issue by RouHim** [BeamMP/BeamMP-Server#205]
**Is your feature request related to a problem? Please describe.**
Due to https://github.com/microsoft/vcpkg/discussions/17738 the server is not able to build on arm64.

**Describe the solution you'd like**
It would be great if it were possible to build on arm64 as easily as on x86.

**Describe alternatives you've considered**
No idea. I guess the rust build solves this :D

**Additional context**
Related discussion on the vcpkg repo is basically dead since two years, microsoft loves linux I guess: https://github.com/microsoft/vcpkg/discussions/17738

**Comment by lionkor** [comment]
We should be able to build the "old" way if we just disable vcpkg in CMakeLists, with a variable for example. That's specifically the second line in the cmakelists which loads cmake/vcpkg or something.
And yes rust server solves this as it already builds on arm.

**Comment by RouHim** [comment]
If I can help you somehow, just ping me.

**Comment by lionkor** [comment]
Works fine, you just have to invoke ./vcpkg/bootstrap-vcpkg.sh before, and put `VCPKG_FORCE_SYSTEM_BINARIES=1` in your environment before

**Comment by lionkor** [comment]
You will need to install the build-time dependencies from the readme, though, of course, before that.
Please try that, I'll close it as this worked for me

**Comment by lionkor** [comment]
FYI there are build scripts in the scripts/ folder you can use :)
