### ISSUE TITLE
Compile Errors on macOS

### ISSUE THREAD

**Issue by max5800** [BeamMP/BeamMP-Server#206]
**General information**
OS:
`macOS 14.1 (23B74) - Intel`
BeamMP-Server Version:
`3.1.3`

**Describe the bug**
Cmake Build runs into errors. 

**To Reproduce**
1. 'brew install lua@5.3'
2. Have CommandLine-Tools installed
3. Run compile commands as documented in the readme. 
4. Get the following output:
https://pastebin.com/5GeQ4f3d 

**Expected behavior**
Get a Successful build.

**Additional context**
Could be an error on level 8, cause I have no idea what I'm doing.

**Comment by lionkor** [comment]
Hi, this is a bug in https://github.com/lionkor/commandline, I will fix it there and upstream the fix into here.

Thanks for reporting this. Would you be willing to help me test it once fixed?

**Comment by max5800** [comment]
Heyho,
thanks for the quick reply! I'm happy to help. 
Just keep me updated when and what to test. 
Danke!

**Comment by max5800** [comment]
@lionkor 
I found two issues:
1. The commandline module wants to have explicitly c++11 which is now added to the cmake file. 
2.  Changed a line in TLuaEngine.cpp from ..nil to ..none 

Related [Pull Request 324](https://github.com/BeamMP/BeamMP-Server/pull/324)

**Comment by max5800** [comment]
pull request merged, fix implemented, will be in next release. 
issue closed.
