### ISSUE TITLE
Minimum Requirements

### ISSUE THREAD

**Issue by toragnetworks** [BeamMP/BeamMP-Server#22]
I've looked around the documentation and couldn't find it - what are the recommended specs for hosting a server as far as CPU/RAM? Sorry if I missed it somewhere.

**Comment by Anonymous-275** [comment]
i would say a virtual core running at 2.5GHz and 50MB of ram

**Comment by Anonymous-275** [comment]
frequency is irrelevant actually and that is minimum as for recommended it's more than 1 core, but the ram usage is really cheap either way

**Comment by lionkor** [comment]
Adding it to the readme, considering this solved.
