### ISSUE TITLE
listen on standard input...

### ISSUE THREAD

**Issue by emlodnaor** [BeamMP/BeamMP-Server#228]
**Is your feature request related to a problem? Please describe.**
I'm running the server as a process from c# code, and trying to write to standard input does not work...

**Describe the solution you'd like**
modify the code so it listens to standard input

**Describe alternatives you've considered**
For now I'll write and read to a file the server mod checks, having rcon could work too...

**Additional context**
no

Acceptance Criteria
---
- [ ] When isatty() is false, the server falls back to normal, buffered i/o
- [ ] Threadsafe
- [ ] Implemented in the TConsole

**Comment by lionkor** [comment]
Edited to add acceptance criteria.

Thanks for your suggestion, I think this is much needed.

**Comment by lionkor** [comment]
Works since v3.2.1
