### ISSUE TITLE
[Bug] Properly check for player timeout

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Server#23]
Problem:

While a player connects, they don't send any pings. This means that they can timeout if their load takes too long. THeartbeatThread kicks after 5 minutes of no-ping.

Solution:

Either send ping from the start and asynchronous to downloads, *or* fix the timeout in some other way. We need timeout to prevent ghost players (players that show up in the player list but aren't actually there).

**Comment by Starystars67** [comment]
New rework of the network can accommodate solutions for this including better ping / health check of clients.

**Comment by lionkor** [comment]
Was increased from 5 minutes to 20 minutes in #44 (v2.3.1). Fix still in progress.

**Comment by lionkor** [comment]
Could/should use SO_RCVTIMEO and SO_SNDTIMEO sockopts in order to do timeouts, which would properly detect any timeouts like that. We can do this on all and any recv() and send() calls. That should do a *real* timeout.

**Comment by lionkor** [comment]
Fix in progress somewhere else, old issue, closing.
