### ISSUE TITLE
Unicycle is counted as a vehicle if you do not have a vehicle spawned

### ISSUE THREAD

**Issue by Starystars67** [BeamMP/BeamMP-Server#246]
I have found that when in a session, if you spawn a unicycle and not a vehicle then when you go to spawn a vehicle after the server will not allow you.

If you remove your unicycle first and then spawn a vehicle it will allow you.

It looks as though the server counts your unicycle on some occasions as if you spawn the unicycle once you have a vehicle in a 1 vehicle per player server it will spawn as expected.

Does this make sense?

**Comment by sla-ppy** [comment]
@lionkor Assign me please!
