### ISSUE TITLE
Util.JsonDecode fails when trying to decode JSON with -Infinity values

### ISSUE THREAD

**Issue by 5TXdYWK** [BeamMP/BeamMP-Server#249]
**Fill out general information**
BeamMP-Server Version: 3.2.0L

**Describe the bug**
Trying to decode the following file will cause an error: [RP_Turdie_V8_-_Broken.json](https://github.com/BeamMP/BeamMP-Server/files/13850252/RP_Turdie_V8_-_Broken.json)
This file is valid JSON and can be parsed in Javascript, for example.

**To Reproduce**
1. Call `Util.JsonDecode(thisFile)`
2. Receive `[LUA ERROR] string given to JsonDecode is not valid json: `

**Expected behavior**
It should parse the JSON regardless of the -Inf values.

**Comment by lionkor** [comment]
That's not -Inf, that's -9e999. That's a completely different problem, since it should be able to handle -inf.

**Comment by lionkor** [comment]
As nlohmann json handles -infinity, but throws out-of-range exceptions when the number doesn't fit in double

**Comment by lionkor** [comment]
Javascript can do this fine, but sadly we can't fix this easily, as it means we'd need to parse the json manually and replace any values > double max with infinity, and so on. Please try replacing these values with null manually, if you encounter this
