### ISSUE TITLE
UDP Improvements

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Server#25]
The way UDP messages are currently handled is less than optimal. 

Two major improvements are to be considered & implemented:

- [ ] Binary serialization between Launcher & Server, deserializing properly into json for the clientside to handle in Lua.
- [x] UDP packet numbering/timestamping to avoid out-of-order packets being processed. When a new packet arrives and it was sent later than the last packet we processed, the new packet should be discarded ("stale").

**Comment by OfficialLambdax** [comment]
The Json is created by the Lua mod of the game, it is send over the Launcher, to the server and from there broadcasted to the other players launcher and then to their Lua mod.

Now you propose this here?:
Lua Mod send Json -> Launcher converts Json to CBOR -> Server relays that data to the other launchers -> Launcher converts CBOR to Json and sends it to the Lua mod -> Lua mod processes the Json.

I think that puts more load on the launcher then necessary. The conversion, i think, takes more time then time is gained by using CBOR.

But i just think that, cant test.

**Comment by lionkor** [comment]
Bandwidth is super expensive, and the larges bottleneck next to CPU at the moment (server side its the only bottleneck). A few CPU cycles to do Json->CBOR is worth it, in theory.

**Comment by OfficialLambdax** [comment]
Well you got the IT background, i cant think of a reason why a few kb per second per car is a problem

**Comment by lionkor** [comment]
It's a pretty large packet, with redundant information. Let's say each pos update packet is 200 B, then the server receives 200 B at 100 Hz or so, makes about 20 kB/s. Let's say we have 5 players (which is a good server pop), we are at 20kB * 5 of received data per second. 100 kB/s. From the server's perspective, that's download. Now, of course, each packet is relayed to all other players, so there is an upload of 100 kB/s * 4 or something like that. 400 kB/s.

That'll already be 3.2 Mb/s upload, plus the 0.8 Mb/s download. A few large (4000+ byte) vehicle packets every now and then, 5 more servers, and up to 10 players, and you can max out any low-to-medium residential connection.

**Comment by lionkor** [comment]
These are back-of-the-envelope calcs, and there's probably an error, but still - its super redundant.

A float is 4 bytes, but instead of 4 bytes, we send around 15 bytes on average.

for example, a float is [][][][] 4 bytes in binary (e.g. in CBOR), but something like "12.5345437342" as a json value (15+ bytes).

It's simply redundant, and doing the json->cbor should be super cheap.

**Comment by lionkor** [comment]
Closing due to move to Rust codebase.
