### ISSUE TITLE
SERVER: IMPORTANT LICENSE CHANGE

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Server#259]
Hey @Anonymous-275 @jojos38 @Starystars67 @20dka @Mack29446 @mio-19 @jimkoen @rgnter @aeroc7 @Qest333 @scisdev,

We're changing the license of this **server codebase** to AGPL-3.0. This is similar to the issue in https://github.com/BeamMP/BeamMP.

Please respond with a short "Okay" or similar message of acknowledgement. If you have any issues or concerns, please make them known.

We will move ahead with the AGPL-3.0 change, we need to know whose code we need to remove for this.

The new license is AGPL-3.0. This is considered an open source license (the current one is not). The current license is a) not really something most of the contributors know or have agreed to formally, and b) is non-free (as in freedom). The GPL family of licenses are based on the fundamental idea of software freedom.

An explanation of the license in practical terms: https://www.gnu.org/licenses/why-affero-gpl.html
Its based on GPL 3.0 which you can find more info about here: https://www.gnu.org/licenses/quick-guide-gplv3.html

Practically, this is BeamMP moving to open source.

**Comment by rgnter** [comment]
Okay from me 👍

**Comment by Mack29446** [comment]
Okay

**Comment by 20dka** [comment]
Okay 💜

**Comment by Anonymous-275** [comment]
Okay

**Comment by Starystars67** [comment]
Okay

**Comment by mio-19** [comment]
Okay

**Comment by aeroc7** [comment]
Okay

**Comment by jimkoen** [comment]
Okay

**Comment by lionkor** [comment]
Qest333 and scisdev's contributions are no longer part of the codebase as far as I can tell, so considering this done @Mack29446
