### ISSUE TITLE
Lua can segfault the server

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Server#3]
I just discovered that Lua is able to segfault the server. It would be nice if we could at least prevent common failures.
Typing `print(nil)` in the console kills it, for example.
I wonder if you can do this from client-side code that interacts with the server's Lua API?

Can we fix this?

**Comment by Starystars67** [comment]
Started and then closed it, All ok?

**Comment by lionkor** [comment]
All this appears in the development channel, and this is potentially a security issue.
