### ISSUE TITLE
Install Script

### ISSUE THREAD

**Issue by DedBash** [BeamMP/BeamMP-Server#30]
Hello I have written an installer script which might be interesting because I noticed that some have to set up the server.
This script contains
- A test if all important things are installed
- The option to download only the server
- The option to run another script to run the server
- The option to install both

to find the whole thing:
[Kiznaiver system´s GitHub](https://github.com/KIznaiver-system/unofficial-BeamMP-Server-installer)
I just want to support the whole project

**Comment by lionkor** [comment]
"!!!Does not work with the server beta version!!!"

There's no such thing. It looks good - just make sure to put which version EXACTLY it's compatible with.
Also, not sure if a GitHub Issue is the place for this.

**Comment by lionkor** [comment]
Good work though - it looks very solid. Any way we can help?

**Comment by DedBash** [comment]
Oh I have clicked the wrong way
And no
