### ISSUE TITLE
Print lua version + implementation on startup

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Server#300]
When running a server and writing plugins for it, I want to know which lua version is used. On linux I can `ldd`, but on Windows I'm lost. The server should print the lua version and any other info it has about it, on startup of the LuaEngine.

**Comment by lionkor** [comment]
This also needs to be added to the `version` command, just like all other library versions we can reasonably query and care about (like openssl)

**Comment by sla-ppy** [comment]
@lionkor Please assign me to this. I'll tackle this issue!

**Comment by sla-ppy** [comment]
@lionkor Suggested for us to add a way to tell which platform we are on along with the rest of the version information.
This will be also added in this issue.
