### ISSUE TITLE
Server isn't starting

### ISSUE THREAD

**Issue by Arales03482** [BeamMP/BeamMP-Server#304]
**Fill out general information**
OS (windows, linux, ...): raspberry pi os running on a raspberry pi debian 11 arm64
BeamMP-Server Version: v3.2.2

**Describe the bug**

**To Reproduce**
Don't know why its happening

**Expected behavior**
Well i expect the server to start but its not working

**Logs**
Please attach the `Server.log` from the run in which the issue appeared, preferably with Debug turned on in the `ServerConfig.toml`.
Server is not starting

**Additional context**
![bild_2024-04-17_005254218](https://github.com/BeamMP/BeamMP-Server/assets/69711892/f185dabf-15b7-48df-b1d3-aab80f010dac)

**Comment by Arales03482** [comment]
Im not really sure the pi is ARM64 though

![image](https://github.com/BeamMP/BeamMP-Server/assets/69711892/b9a0ea8e-528b-453f-aff4-f3c9de15e557)

**Comment by lionkor** [comment]
You're not downloading the file correctly, I assume. Also please **NEVER** run it as `sudo`. Reopen if the issue reappears with a correctly downloaded file.
