### ISSUE TITLE
Blacklist certain props/objects in Official BeamMP servers to prevent troll attacks

### ISSUE THREAD

**Issue by Racxr** [BeamMP/BeamMP-Server#334]
**Is your feature request related to a problem? Please describe.**
People, in this case trolls, commonly love to use props like the 'giant flail' to mess around and destroy peoples cars in the official servers, it's simply annoying and having to constantly delete them can be tiring for some users trying to enjoy playing.

**Describe the solution you'd like**
If possible, completely blacklist/block a certain amount of props, if not all. They are commonly used by trolls and that against the actual purpose of the prop (i.e swing it around with node grabber and hit people). The blacklist could simply delete the prop the moment it gets spawned, just like cars get removed on servers with user vehicle spawn limits.
_Additionally, but not neccessarry:_ Blacklist/block ramp truck and rocket bus, as they similarly only ever get used by trolls.

**Describe alternatives you've considered**
N/A

**Additional context**
This was brought up by someone else on the official discord server. The users request is if it's possible to make certain objects (for example: giant flail, brick wall, etc..) blacklisted in the official servers. There is no point for such objects to really be usable/spawnable in these servers as there simply is not much you can reasonably do. To add to this and as mentioned above; trolls love to use these props, and 9/10 times it is only trolls using them against their original purpose.

**Comment by Mack29446** [comment]
This doesn't apply to this repo - but we can certainly implement this on the official servers.
