### ISSUE TITLE
Lua on Linux: std output file is closed

### ISSUE THREAD

**Issue by 5TXdYWK** [BeamMP/BeamMP-Server#34]
```lua
  local tableFile = readJson(rootPath .. fileID .. "/" .. jsonFile .. ".json")
```

```lua
  if tableFile == nil then
    local file, err = io.open(rootPath .. fileID .. "/" .. jsonFile .. ".json", "w")
    io.output(file)
    io.write('{"' .. tableKey .. '": null' .. "}")
  end
```

Fails on `io.write`.

![image](https://user-images.githubusercontent.com/82390521/124277919-fa9b1700-db1b-11eb-940f-4d6a36784bec.png)

**Comment by lionkor** [comment]
Hello! 

I'm not very experienced in Lua programming, so I will ask you to clarify; Are you trying to set the standard output file to some file you opened, and then try to write to that?

**Comment by lionkor** [comment]
@5TXdYWK I need more info, otherwise I have to close this
