### ISSUE TITLE
[Debian 12] - [x86_64] - The Server is unable to read AuthKey from the ServerConfig.toml file. 

### ISSUE THREAD

**Issue by cptDeeJay** [BeamMP/BeamMP-Server#340]
**Fill out general information**
OS (windows, linux, ...): Linux - Debian GNU/Linux 12
BeamMP-Server Version: v3.4.1

**Describe the bug**
The Server is unable to read AuthKey from the ServerConfig.toml file or the file itself.
After installing and configuring server with steps given in official documentation, server is launching with error.
`No AuthKey specified in the "ServerConfig.toml" file. Please get an AuthKey, enter it into the config file, and restart this server.`
Even that correct AuthKey generated from Keymaster is placed. 

**To Reproduce**
1. Performinstallation guide steps  1-4 from official Docs
2. Paste AuthKey into the ServerConfig.toml file.
3. Attempt to launch the Server
4. Observe the Issue

**Expected behavior**
Server is able to launch propertly after compleating all the steps under "Server Installation" in official Docs

**Logs**
Cannot attach logs because of nature of the issue.
No Logs are generated as server is not starting.
Attached logs are copy-pasted from Debian Terminal

**Additional context**
Please note that all steps were done on root user, no additional users were created as this is supposed to be test of the host machine performance.
Used executable is 'BeamMP-Server.debian.12.x86_64' 
Host machine information:
Intel i5-6400
16Gb of DDR4 RAM

*Less serious part*:
In addition please note that I'm not very good with Unix/Gnu/Linux based systems, so there is high chance of my skill issue while configuring the server, however confirming that all required dependencies are correctly installed issue is still occuring. 

![obraz_2024-06-20_030028216](https://github.com/BeamMP/BeamMP-Server/assets/173320428/7bd5e34d-23fe-433c-844c-c49a2fa67bca)
[log.txt](https://github.com/user-attachments/files/15907103/log.txt)
![obraz_2024-06-20_030013515](https://github.com/BeamMP/BeamMP-Server/assets/173320428/34ef29a4-3474-44ea-9c74-69517669fb7e)

**Comment by O1LER** [comment]
@cptDeeJay 
Have you saved the changes before exiting nano?

Have you tried deleting the toml and generating a fresh one trough starting the server?

**Comment by O1LER** [comment]
Just tested 

```
# This is the BeamMP-Server config file.
# Help & Documentation: `https://docs.beammp.com/server/server-maintenance/`
# IMPORTANT: Fill in the AuthKey with the key you got from `https://keymaster.beammp.com/` on the left under "Keys"

[Misc]
# You can turn on/off the SendErrors message you get on startup here
SendErrorsShowMessage = true
# If SendErrors is `true`, the server will send helpful info about crashes and other issues back to the BeamMP developers. This info may include your config, who is on your server at the time of the error, and similar general information. This kind of data is vital in helping us diagnose and fix issues faster. This has no impact on server performance. You can opt-out of this system by setting this to `false`
SendErrors = true
# Hides the periodic update message which notifies you of a new server version. You should really keep this on and always update as soon as possible. For more information visit https://wiki.beammp.com/en/home/server-maintenance#updating-the-server. An update message will always appear at startup regardless.
ImScaredOfUpdates = false

[General]
ResourceFolder = "Resources"
Map = "/levels/derby/info.json"
MaxPlayers = 16
Description = "Test"
# Add custom identifying tags to your server to make it easier to find. Format should be TagA,TagB,TagC. Note the comma seperation.
Tags = "Freeroam"
Port = 30023
Private = true
Debug = false
Name = "Test"
# Whether to log chat messages in the console / log
LogChat = false
MaxCars = 10
# AuthKey has to be filled out in order to run the server
AuthKey = "d43ae6f9-78ba-4e65-8a0e-380db9f14d76"

```

Works for me.
The auth key i used is non-valid, but since the server is set to private it doesnt check with the backend. Even if set to public, it would return an invalid authkey error, not a missing authkey

**Comment by cptDeeJay** [comment]
> @cptDeeJay 
> Have you saved the changes before exiting Nano?
> 
> Have you tried deleting the toml and generating a fresh one trough starting the server?

@O1LER Thank you very much for your help.
No, deleting config didn't help to fix my issue. However, it looks like the executable I downloaded was corrupted as after removing and re-downloading BeamMP, the server runs properly, and I think everything is working fine now (couldn't join the server, not BeamMP related)

Once again, thank you for the help

**Comment by cptDeeJay** [comment]
Ok I need help once again, I've manage to join the server, however after consistent 1.5 to 2 mins connection is being terminated. 
I know that it's not issue with my internet provider, and also I don't want to create new ticket as it might be my skill issue.
I've tried to restart both host machine and executable, I tried modifing config, I also tried working on different ports, nothing help. 
Weird is also that the Users is being disconnected with no disconnection reason in console. 

Should I create new ticket with that issue ?

![obraz_2024-06-21_000712948](https://github.com/BeamMP/BeamMP-Server/assets/173320428/40fe6a21-86da-4311-8b83-c6f2e7c23992)
![obraz_2024-06-21_000721601](https://github.com/BeamMP/BeamMP-Server/assets/173320428/1251da25-1cc3-494c-abe9-60bdc5a5beb1)
![obraz_2024-06-21_000733644](https://github.com/BeamMP/BeamMP-Server/assets/173320428/fa82e8ce-a468-4031-a29d-68c8ef259832)
![obraz_2024-06-21_000748643](https://github.com/BeamMP/BeamMP-Server/assets/173320428/21f9b607-673b-427d-86ba-6e32156ff832)
[log.txt](https://github.com/user-attachments/files/15920571/log.txt)

**Comment by lionkor** [comment]
Hi, for these issues please either 1) make a forum post on https://forum.beammp.com or 2) open a support thread in our discord https://discord.gg/beammp. I'm not sure if these are known bugs, and our support team can likely help you better with this than our dev team :)

If it turns out that either of those issues are bugs, please make a new issue!

Thanks for taking the time to write out your problems and provide screenshots nonetheless, it's very helpful and I wish more bug reports were this thorough.
