### ISSUE TITLE
BeamMP Staff Tag Not Disabling

### ISSUE THREAD

**Issue by trebor8820** [BeamMP/BeamMP-Server#346]
OS (windows, linux, ...):
BeamMP-Server Version: Current

BeamMP Staff "blue" nametag overrides settings provided in the forum.

**To Reproduce**
1. In BeamMP Account/Profile Settings, change Title to reflect "None" or "Early Access"
2. Test in-game; results still give "staff" tag.
3. Try logging out and back in, test again.  Results same.

**Comment by Mack29446** [comment]
Not a server issue - this is caused by the backend. Infra team will investigate and get back to you separately
