### ISSUE TITLE
Unique BeamMP IDs are hard to use

### ISSUE THREAD

**Issue by carsakiller** [BeamMP/BeamMP-Server#353]
I would like to add to #212.

Currently, it is pretty difficult to actually use the unique BeamMP identifiers. On top of what is mentioned in #212, there is no way to get a player's BeamMP ID outside of having them join a server. The BeamMP UI in BeamNG should display the player's BeamMP ID so that someone can easily tell you their unique identifier without having to join a server first. This would be extremely helpful for dis/allow listing.

**Comment by WiserTixx** [comment]
The unique id for a player can be found at https://forum.beammp.com/u/{username}.json under `user_id`
Tho I agree, there should probably be an easier method of viewing it.

**Comment by carsakiller** [comment]
@WiserTixx that is actually really helpful, thanks! Do you know if usernames **must** be unique? Would really throw a wrench in things if they were not, but I imagine they must be then.

**Comment by Mack29446** [comment]
Usernames _can change_ and should not really be used as a unique identifier.

**Comment by carsakiller** [comment]
@Mack29446, yeah, I am mainly just looking to be able to easily grab friends' BeamMP IDs in the moment. It would be nice if they just knew it from the UI, but I am happy for now to use this method to exchange their usernames for the BeamMP IDs.

**Comment by lionkor** [comment]
This issue isnt really specified that well. Essentially, you want the BeamMP ID in the UI, right? Because the Server gives you the ID at any point via MP.GetPlayerIdentifiers, so the only improvement here is the UI of the game. If thats the case, I'll move this issue to the game's repo.

Let me know if I'm missing something

**Comment by carsakiller** [comment]
Yes. I want to be able to easily find someone's BeamMP ID without having to make them first join my server so that I can pull their BeamMP ID using `MP.GetPlayerIdentifiers()`.

The solution I propose in this issue is to add the BeamMP ID to the UI or through other means make it obvious to them. I initially didn't know about `MP.GetPlayerIdentifiers()` (hence the edit) so I created this issue here as I am sort of adding on to #212, but it probably belongs in the client or launcher/bridge.

**Comment by Starystars67** [comment]
We are working on getting it done so you can see your BeamMP ID in the client.

@WiserTixx ^

**Comment by WiserTixx** [comment]
As per https://github.com/BeamMP/BeamMP/pull/656 you can now see/copy your id in-game without having to join a server. This feature is currently in the early access release for further testing and should be in the next public release.
