### ISSUE TITLE
Documentation Needs to be updated again

### ISSUE THREAD

**Issue by synth80s** [BeamMP/BeamMP-Server#36]
Include dependencies:
- libwebsocketpp-dev

Install submodule commands
- git submodule init 
- git submodule update

**Comment by lionkor** [comment]
I will add libwebsocketpp-dev, but submodule stuff is handled by `git clone --recursive`. You can always do `git submodule update --init` if you missed that, but I don't think that should be included. We could do a "troubleshooting" section for that kind of thing - that would be a great idea.

**Comment by lionkor** [comment]
Probably should also add an "how to update" section, which would then need and use submodule update.

**Comment by lionkor** [comment]
for the record, it's going to be `git clone --recurse-submodules`, which is important considering dependency changes in #44
