### ISSUE TITLE
Beammp server windows doesn't recognise an auth key

### ISSUE THREAD

**Issue by qtrewq** [BeamMP/BeamMP-Server#361]
**Fill out general information**
OS (windows, linux, ...): Windows 11 Pro for Workstations 23h2 Build 22631.4112
BeamMP-Server Version: 3.4.1
Ryzen 7800X3D, 32gb ram

**Describe the bug**
Beammp Server will not recognise an auth key when entered into the ServerConfig.toml file. 

**To Reproduce**
1. Launch server executable in command prompt with path
1b. OR Launch server executable from file explorer
2. Enter an auth key into the ServerConfig.toml file
3. Repeat step 1 or 1b

**Expected behavior**
Server launches with no issues

**Logs**
[Server.log](https://github.com/user-attachments/files/16819279/Server.log)
Command line output
```
[30/08/24 11:38:14] [ERROR] No AuthKey specified in the "ServerConfig.toml" file. Please get an AuthKey, enter it into the config file, and restart this server.
[30/08/24 11:38:14] [INFO] Closing in 10 seconds
```

**Additional context**
Also did not recognise either of my two auth keys on a server hosting service, could be a problem with my auth keys?

**Comment by WiserTixx** [comment]
Hey, please contact support in [our discord server](https://discord.gg/beammp).

**Comment by Protogen187** [comment]
Issue resolved within the Support channels.
Port was already in use

**Comment by qtrewq** [comment]
Solved! Don't use the same port for any other services.
