### ISSUE TITLE
Add reason to onPlayerAuth cancellation

### ISSUE THREAD

**Issue by carsakiller** [BeamMP/BeamMP-Server#368]
**Is your feature request related to a problem? Please describe.**
When rejecting a player joining during authorization (`onPlayerAuth`), all you can do is `return 1` and they get a generic “you are not allowed to join this server” message.

**Describe the solution you'd like**
I would like to be able to also return a reason for them being denied access, something like so:
```lua
return 1, "A clear reason as for why you are currently not allowed to join"
```

**Describe alternatives you've considered**
There aren't really any. `MP.DropPlayer()` cannot be used (which allows providing a reason) because the player has not actually joined and been assigned an ID yet.

**Comment by WiserTixx** [comment]
This is actually already possible, if you return a string directly that will kick the player and show that message

`return "You have been banned"`
![image](https://github.com/user-attachments/assets/da4256bd-959b-4cf4-9f2e-5e23b3ad49e2)


  <table>
    <tr>
      <td>
        <img src="https://github.com/user-attachments/assets/4bf954d6-5591-4056-872b-bb2697596393" alt="Image" width="2000" >
      </td>
      <td style="vertical-align: top; padding-left: 10px;">
        <div>
<a href="https://github.com/BeamMP/BeamMP-Server/blob/7f69e336a9fbf9fc13e641bf2a9882482599c9f5/src/TNetwork.cpp#L405" target="_blank">TNetwork::Authentication in TNetwork.cpp</a><br><br>
          1: The onPlayerAuth event is called <br> <br>
          2: We loop over the return values <br> <br>
          3: We check if it's a string and if it is, we set that as the reason and set NotAllowedWithReason to true <br> <br>
          4: If no lua script returned 1 <br>(NotAllowed == false) and NotAllowedWithReason is true we kick them with Reason
        </div>
      </td>
    </tr>
  </table>

**Comment by carsakiller** [comment]
So it is! Thank you, @WiserTixx! I have just been going off what the [docs](https://docs.beammp.com/scripting/server-reference) say, and there was no mention of the ability to do this. In hindsight, I should've checked the code, but I am not very familiar with C++.

I'll open a PR to add to the docs that this is possible.
