### ISSUE TITLE
Is there a way to use BeamMP on Oracle Linux 9?

### ISSUE THREAD

**Issue by IYO-OYI** [BeamMP/BeamMP-Server#375]
Hello, I am trying to build a server using an Oracle ARM server. Is there a way to use Oracle Linux 9 on it?

**Comment by O1LER** [comment]
Have you tried running the prebuilt arm executables? Chances are that for example the ubuntu one works on oracle.

If not, follow the build instructions in the readme to build an executable yourself

**Comment by IYO-OYI** [comment]
> Have you tried running the prebuilt arm executables? Chances are that for example the ubuntu one works on oracle.
> 
> If not, follow the build instructions in the readme to build an executable yourself

Pre-compiled files are failing with the error "error while loading shared libraries: liblua5.3.so.0: cannot open shared object file: No such file or directory" during execution. Oracle Linux 9 only has the liblua5.4 version. Trying to compile BeamMP manually following instructions, using cmake -S . -B bin -DCMAKE_BUILD_TYPE=Release, results in errors related to the vcpkg package. Please help.

**Comment by O1LER** [comment]
Thats a bit above my paygrade, but i would guess if liblua5.3 is not available so would be liblua5.3_dev, which is needed to build

**Comment by lionkor** [comment]
@IYO-OYI please post the complete logs of the build that fails

**Comment by 20dka** [comment]
> so would be liblua5.3_dev, which is needed to build

Building is possible with lua 5.4 as well

**Comment by IYO-OYI** [comment]
I would like to thank everyone for their assistance. Despite our efforts, using gemini 1.5 pro did not yield a successful resolution. As such, we are considering switching to the Ubuntu version.

**Comment by lionkor** [comment]
Yeah, a random word generator wont help you. We have documentation, which you can read. I would recommend Debian as a good base to run servers on!

Good luck!
