### ISSUE TITLE
ServerConfig.toml always reset

### ISSUE THREAD

**Issue by BreizhHardware** [BeamMP/BeamMP-Server#400]
**Fill out general information**
OS (windows, linux, ...): Linux (in a pterodactyl container)
BeamMP-Server Version: latest

**Describe the bug**
When you try to edit the ServerConfig.toml, when you restart the server it fallback to the default one.

**To Reproduce**
1. Edit the server-config.toml
2. Restart the server

**Expected behavior**
The change in ServerConfig.toml is persistant

**Comment by BreizhHardware** [comment]
After further search in the file off the egg it's a bug from the egg sorry of the useless issue

**Comment by O1LER** [comment]
Its not a bug, its a core pterodactyl mechanic. Changes need to be done trough the panels Startup menu
