### ISSUE TITLE
Can't build the server on Raspbian, is there any solution?

### ISSUE THREAD

**Issue by R2D2VaderBeef** [BeamMP/BeamMP-Server#43]
**Fill out general information**
OS (windows, linux, ...): Raspbian Buster
BeamMP-Server Version: v2.2.0

**Describe the bug**
I believe this is an issue with the dependency `libboost1.70-all-dev`.  The latest version available to install is `libboost1.67-all-dev`. I have this installed. However, after running `make` the build terminates with the following error:
```
/home/pi/Documents/BeamMP Server/BeamMP-Server/src/Http.cpp:9:10: fatal error: boost/beast/ssl.hpp: No such file or directory
 #include <boost/beast/ssl.hpp>
```

**To Reproduce**
1. Start up a Raspberry Pi with Raspbian Buster installed and everything updated.
2. Try to install the dependencies for building. Note that `libboost1.70-all-dev` is not available.
3. Clone the git repo and checkout tags/v2.2.0
4. Run `cmake .` and then `make`

I realise that this isn't really an issue with BeamMP-Server and more a lack of compatibility. However, one official page said that the server had been run on a Raspberry Pi. If it is possible, then how can I do it? Do I need to build from source on a different OS, or run a different OS on my Pi altogether? Or something else?

If it isn't possible, please let me know. I can try and find another way to host the server.

Thanks!

**Comment by lionkor** [comment]
Hello!

We do support running on Debian, of which Raspbian is a derivative, so it should work. The boost dependency issue has been a problem for a good bit, but is an issue with Debian, not with us.

The best thing you can do is look up how you can get boost 1.70+ onto a Debian system.

I'd be more than willing to help you get this going in a call on discord (@ me there if you're interested), but for general completeness, you want to follow [this guide](https://www.boost.org/doc/libs/1_76_0/more/getting_started/unix-variants.html), here's my shortened version:

(I know it looks scary, its not!)

0. Update your system:

```sh
sudo apt update -y && sudo apt upgrade -y
```

1. Let's make sure you have all the things we need:

```sh
sudo apt install build-essentials tar wget
```

2. `cd` into a directory of your choice. Now download boost:

```sh
wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
```

3. Extract

```sh
tar -xzvf boost_1_76_0.tar.gz
cd boost_1_76_0
```

4. Build & Install

```sh
./bootstrap.sh
./b2 install
```
... and this can take a while, up to an hour or so.
Make sure your Pi is sufficiently cooled for this. If you don't want to wait so long, refer to the guide above, it explains how you can pick to only build & install what you need.

As I said before, feel free to contact me on Discord @`Lion#5934`.

**Comment by R2D2VaderBeef** [comment]
Thanks a lot! I'll try this, and will contact you on Discord if I have any issues.

**Comment by R2D2VaderBeef** [comment]
It worked! Thanks a lot.
