### ISSUE TITLE
README build instructions are incomplete

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Server#5]
The current build instructions are incomplete, we should either remove them or write a more complete and correct instructions.

Do we need Unix, Windows, Mac? Which toolchains do we support / recommend? Do we offer build instructions at all?

**Comment by Anonymous-275** [comment]
unix and windows, for now, recommend MSVC and gcc with O2.

**Comment by lionkor** [comment]
done in d8e1d389bfd9511d5ab1ad3e2d6857597c1716fc
