### ISSUE TITLE
Reverse Proxy server w/ Traefik

### ISSUE THREAD

**Issue by ngysling** [BeamMP/BeamMP-Server#52]
Hey all, trying to use a reverse proxy (traefik) to be able to connect to the beammp server. Here are my traefik labels. 

```
 - --entryPoints.tcpbeammp.address=:30814                                                                                
 - --entryPoints.udpbeammp.address=:30814/udp                                                                            
 - "traefik.enable=true"                                                                                                 
 - "traefik.docker.network=proxy"                                                                                        
 - "traefik.tcp.services.beammp.loadbalancer.server.port=30814"                                                          
 - "traefik.tcp.routers.beammp.rule=HostSNI(`beammp.domain.us`)"
```

I can connect fine locally, but my friends get a "connection refused" error. I know this could be a plethora of things beyond beamMP, but I was hoping someone has done this before here and could just guide me to a working example. Cheers.

**Comment by lionkor** [comment]
Hi!

I want to quickly get some things out of the way that are obvious and probably redundant: 

1. Check your firewall - it has to allow what youre doing there
2. Make sure you have ports forwarded, like the 30814, and (im not sure what your setup is) ensure that you use 30814 as the port in the ServerConfig (!!!).

**Comment by ngysling** [comment]
Hello, and thank you for the prompt response. Traefik is a reverse proxy like NGINX or Caddy. It directs all traffic over 443 and diverts it to the correct application. My firewall rules allow everything else, and the ports that need to be forwarded (443) were already forwarded. 

I know this can be well beyond the scope of the application, I was just hoping I could get the attention of someone who has done this before.

**Comment by lionkor** [comment]
I have a suspicion about what the problem might be.

The port that you reach the server from the internet from and the port that the server itself opens have to be the same port number.

For example, assume:
- The ServerConfig.toml specifies port 12345
- Your domain is `example.com`

Then the server has to be reachable on `example.com:12345`.

You can route that through all sorts of proxies and whatnot, but in the end the server's port and the port towards the internet have to be the same.

**Comment by lionkor** [comment]
@longdas ?

**Comment by lionkor** [comment]
Reopen if there is new info on this @longdas, for now i'll consider it closed as solved.
