### ISSUE TITLE
[Feature Request] Provide health endpoint

### ISSUE THREAD

**Issue by RouHim** [BeamMP/BeamMP-Server#65]
**Is your feature request related to a problem? Please describe.**
No it is not related to a bug, it is a suggestion for improvement.

**Describe the solution you'd like**
Some kind of endpoint through which I can check the health of a running server (without evaluating the log).

**Describe alternatives you've considered**
Evaluating the log.
Query something to the query port?

**Additional context**
I am working on improving the docker container for beammp and what I am missing is a health status of running server. In case of a misconfiguration or similar it can happen that the server is running but in a faulty error state.

**Open questions**
Is there even an "error state" that the server can reach where the server process continues to run without aborting with an error code.

**Comment by lionkor** [comment]
Cool idea!

> Is there even an "error state" that the server can reach where the server process continues to run without aborting with an error code

The server either recovers from an error gracefully or closes (fatal).

When people repeatedly fail to connect or download, there is currently no error state that records it. We could do that, though. Adding a health endpoint that currently just says "everything's fine" as long as the server is running could be done. We could add more monitoring later. 

What's a common transaction you'd like to see here? Just an HTTP endpoint, responds with a json, with what sort of values? `good`, `bad`, etc.? A percentage (somehow)?

**Comment by RouHim** [comment]
So I need an endpoint against which I can execute a busybox command. 
This could be for example a wget on a http endpoint.
The only important thing is that the called command returns one of the two exit codes:
- 0: success - the container is healthy and ready for use
- 1: unhealthy - the container is not working correctly

I take the option that is easiest for you. If this is a http end point then I'm fine with that.

**Comment by Starystars67** [comment]
I too would like to see a HTTP endpoint made available. This could be then used for health checking but also stats collection and what not without querying the backend for that information.

This could then be used to generate dashboards for controlling servers too (Not like I have this in the works anyway) xD

**Comment by jimkoen** [comment]
### We now have a working HTTP Server on [branch `rewrite-lua`](https://github.com/BeamMP/BeamMP-Server/tree/rewrite-lua).

[Please make suggestions on what metrics you'd like to have available on what endpoints in this issue.](https://github.com/BeamMP/BeamMP-Server/issues/69)
