### ISSUE TITLE
[Feature Request] Enable macOS Toolchain Compatibility

### ISSUE THREAD

**Issue by jimkoen** [BeamMP/BeamMP-Server#66]
**Is your feature request related to a problem? Please describe.**
Currently the 'BeamMP-Server' project will not compile on macOS Monterey with Apple Clang 12.0.
I assume this is a systemic issue and won't work across all macOS versions, since macOS is rarely a compile target
in C++ application development.

**Describe the solution you'd like**
Either a project that works with the macOS toolchain (Clang/Cmake) and compiles on Mac or a **docker** based build and test environment that includes all dependencies needed to build BeamMP-Server, as well as run and test it in the container.
(Keywords are automated testing and platform independence)

**Comment by lionkor** [comment]
This is a nice idea, I like it. We should sit down together to do this.

**Comment by lionkor** [comment]
I'm not sure, is this done with #67?

**Comment by jimkoen** [comment]
> I'm not sure, is this done with #67?

It's somewhat hard to say, as beammp-server uses a lot of libraries that aren't natively present on macOS.
Users need to modify the cmakelists.txt file and add the respective paths to the needed libraries (install paths can change depending on the version of macOS and the installation method (manual, brew, macports etc).

For general compatibility it would be great to check all platform agnostic ifdefs if they include the check for the `__APPLE__` compiler provided constant. 

Another thing that would help for macOS development would be to either use a package manager like Conan or VCPackage, or to compile a list of all third party libraries that may not be present on a standard OS install.

**Comment by lionkor** [comment]
I went and cleaned up all ifdefs in fd7bea0f36c363e1efe67b76db37611cbc4235d5. There's now a `BEAMMP_APPLE` define which is handled everywhere (as far as I can tell). 

The libraries are an issue, they might have to all become git submodules and be built by CMake, probably via [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html). 

Or, of course, Conan or VCPkg
