### ISSUE TITLE
[Feature Request] Add OpenAPI specification for http server endpoints

### ISSUE THREAD

**Issue by jimkoen** [BeamMP/BeamMP-Server#69]
Related Issue: https://github.com/BeamMP/BeamMP-Server/issues/65

This issue is for drafting a API specification for the upcoming inbuilt HTTP Server.

Please post requests for specific endpoints below.

**Comment by RouHim** [comment]
Can you please give ma a short curl example for the existing endpoint with output data?

**Comment by jimkoen** [comment]
> Can you please give ma a short curl example for the existing endpoint with output data?

This thread was more thought of as an ideas thread. I assume the people interested in an HTTP Server know what kind of information they want to retrieve from a server instance and could therefore post ideas here.

If you read my reply in #65 , you'll see it's still upcoming, i.e. currently neither on the rewrite-lua or master branch. I'm waiting for Lion to merge my changes into rewrite-lua. Once that happens I'll implement an example route for use with cURL.

If you manage to compile my PR there's still a bug in the config that I'm waiting for Lion to help me fix. I expect this to be done towards the end of the day.

**Comment by RouHim** [comment]
Awesome, thank you for tackling this feature request so fast. As I wrote in https://github.com/BeamMP/BeamMP-Server/issues/65#issuecomment-973950358 it is pretty much up to. As long I can run any kind of test against it. For the beginning we could start with simple HTTP response codes like a 200 (OK) if everything is fine; and a 500 (Internal Server Error) if something is wrong.

Example:
```bash
> curl -I http://localhost:1337/health
HTTP/1.1 200 OK
```


```bash
> curl -I http://localhost:1337/health
HTTP/1.1 500 Internal Server Error
```

**Comment by jimkoen** [comment]
> Awesome, thank you for tackling this feature request so fast. As I wrote in [#65 (comment)](https://github.com/BeamMP/BeamMP-Server/issues/65#issuecomment-973950358) it is pretty much up to. As long I can run any kind of test against it. For the beginning we could start with simple HTTP response codes like a 200 (OK) if everything is fine; and a 500 (Internal Server Error) if something is wrong.
> 
> Example:
> 
> ```shell
> > curl -I http://localhost:1337/health
> HTTP/1.1 200 OK
> ```
> 
>  ```shell
> > curl -I http://localhost:1337/health
> HTTP/1.1 500 Internal Server Error
> ```

I added a health endpoint under `/health` to my PR:

```sh
> curl -I --insecure https://localhost:<port>/health
HTTP/1.1 200 OK
```
This will deliver a HTTP 200 Status and a '0' in plaintext when everything is working and a '1' and 500 if there is something wrong.
Currently it will always deliver 200 OK, we're still investigating how to best pass errors and internal problems to the http handlers.

Note that the server is only available using HTTPS and will use self signed certificates if nothing else is specified in the ServerConfig.

Three new options have been added to the ServerConfig to control the http server:
```toml
SSLKeyPath = "path/to/your/keyfile" # Location of the SSL Keyfile, will auto generate when not provided
SSLCertPath = "path/to/your/certfile" # Location of the SSL Certificate, will auto generate when not provided
HTTPServerPort = 1337
```

**Comment by RouHim** [comment]
Ok great thank you, but let's go with ssl default port 443 😁

**Comment by lionkor** [comment]
>  ssl default port 443

I'd recommend against this, <1024 ports are reserved for root on \*nix. I'd put a custom port, since I wouldn't like to see someone run a server as sudo. We should pick a reasonable port number for default.

**Comment by lionkor** [comment]
If you wanted 443, the correct way to do it would be to run the server with some other port and then put up a reverse proxy to map it to 443.

**Comment by RouHim** [comment]
Alright thanks for the explanation 👍

**Comment by lionkor** [comment]
Some endpoint ideas I could see being useful:
- `GET /players` returns a json object with all players, their names, etc.
- `GET /settings` returns a json object with all "General" settings (except AuthKey etc.)

**Comment by Starystars67** [comment]
Just my 2 cents but what about if you bound it to the server port + 1? Plus add this as a config setting to the server config file.

Something like:
```
HTTP Endpoint: 30815
Game Endpoint: 30814
```

As for suggestions on endpoints. Maybe we could do the following:
`/health` -> this returns a simple OK or to be a little more valuable something that is simple like the player count, packets per second and uptime.
`/stats` -> this would return the full list of stats like uptime, player count, packets per second, vehicles in the server and maybe any others that anyone can think of.
`/info` -> this returns something like the same data as heartbeat so the players list, the max players, the description, the mods and other details.
`/players` -> returns just the player list. 

All of these routes would be provided as json based data too for easier use by other applications.


Off the back of this we should also add the ability to allow Lua to register endpoints too so that people can use these in their own scripts. Plus they could build their own authentication into these routes for their purposes.

**Comment by 5TXdYWK** [comment]
>what about if you bound it to the server port + 1

Just have it set in the config, much clearer.

**Comment by Starystars67** [comment]
> > what about if you bound it to the server port + 1
> 
> Just have it set in the config, much clearer.

Ah sorry I thought this is what I did say by saying 
> Plus add this as a config setting to the server config file.

Ah well ;P

**Comment by 5TXdYWK** [comment]
@Starystars67 sorry i'm functionally illiterate

**Comment by 20dka** [comment]
i suggest a `/cat` endpoint: returns an ascii kitty

**Comment by jimkoen** [comment]
> Just my 2 cents but what about if you bound it to the server port + 1? Plus add this as a config setting to the server config file.

Because not every environment can support two Webservers running on the same port (NAT'ed environments being the keyword here). We can let this be the default configuration though, the port I've chosen was rather arbitrary.

**Comment by jimkoen** [comment]
[Created a first draft for the API spec](https://github.com/jimkoen/BeamMP-Server/blob/69-open-api-based-http-server/openapi.yml)

**Comment by lionkor** [comment]
You can see the current status of the draft here https://github.com/BeamMP/BeamMP-Server/blob/feature-9/openapi.yml

**Comment by Erani0** [comment]
I would like it if there is only 1 page ```/All ``` Or ```/Server``` where everything is listed instead of individual pages this makes it easier to query in general

**Comment by lionkor** [comment]
@Erani0 thats a nice idea for users, I think we should do that. It wouldnt be easier to query from a programmer's perspective, though - we will have endpoints to access common stats, for example, of course
