### ISSUE TITLE
`make` fatal error: any: No such file or directory

### ISSUE THREAD

**Issue by ghost** [BeamMP/BeamMP-Server#7]
Hi, when I run make command in BeamMP-Server directory after running `cmake .` and with all dependencies installed I get this error in the console :
```[  4%] Building CXX object CMakeFiles/BeamMP-Server.dir/src/Console.cpp.o
In file included from /root/BeamMP-Server/src/Console.cpp:9:0:
/root/BeamMP-Server/include/Lua/LuaSystem.hpp:10:15: fatal error: any: No such file or directory
 #include <any>
               ^
compilation terminated.
CMakeFiles/BeamMP-Server.dir/build.make:94: recipe for target 'CMakeFiles/BeamMP-Server.dir/src/Console.cpp.o' failed
make[2]: *** [CMakeFiles/BeamMP-Server.dir/src/Console.cpp.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/BeamMP-Server.dir/all' failed
make[1]: *** [CMakeFiles/BeamMP-Server.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
```
I'd be thankful for any help or advice !

**Comment by lionkor** [comment]
Hey there! It looks like your compiler does not support C++17. Please make sure your compiler supports it. If you're on linux, you're likely using `gcc`. If you need further help, post the output of `cc --version` here.

**Comment by ghost** [comment]
Hi, thanks for responding my issue. I tried to reinstall my V.P.S. with Debian 10 before seeing your message... and it runs now, I can launch `./BeamMP-Server` but when I try to join with _BeamMP Client_ I get :

`> Segmentation fault`

![image](https://user-images.githubusercontent.com/40071801/104361008-2c8ad380-5512-11eb-9ee7-8a1e9210f944.png)

Thanks again for your prompt reponse.

**Comment by coledeck** [comment]
I get the same thing, SIGSEGV as soon as someone joins. Using Arch Linux.

**Comment by lionkor** [comment]
So, after some investigation, it seems this is a problem with the `master` build right now, related to curl.

For a working and stable version, for now, please use the v1.20 release branch.

To do this, first, switch to it with `git checkout tags/v1.20` and then rebuild.

We're looking into the issue and will push a change as soon as possible. For now, I'll create a new issue for it, so we can track the progress.

**Comment by lionkor** [comment]
Likely resolved with the latest PR. Closed.
