### ISSUE TITLE
[Bug] Server hangs when input is received in the console window

### ISSUE THREAD

**Issue by weskoerber** [BeamMP/BeamMP-Server#77]
**Fill out general information**
OS (windows, linux, ...): Windows 10
BeamMP-Server Version: 2.2.0

**Describe the bug**
Server hangs when input is received in the console window

**To Reproduce**
1. Start BeamMP-Server
2. Type into console window
3. Try to connect to server

**Expected behavior**
Server should not hang when input is received in the console window

**Logs**
[BUG-Server.log](https://github.com/BeamMP/BeamMP-Server/files/7795184/BUG-Server.log)

**Additional context**
N/A

**Comment by lionkor** [comment]
Hello, please update to the latest public release 2.3.3, and send another log if the issue persists

**Comment by weskoerber** [comment]
I don't see this happening with 2.3.3.

**Comment by lionkor** [comment]
3.0.0 brings a huge amount of changes, I hope there is no regression for this bug, we will see :) Enjoy

**Comment by lionkor** [comment]
Still a bug?

**Comment by weskoerber** [comment]
> Still a bug?

I believe updating from 2.2.0 to 2.3.3 solved the issue. I haven't played since before 3.0.0 was released so I haven't tested it.

**Comment by lionkor** [comment]
Thanks reopen with new info if it shows up again.
