### ISSUE TITLE
[Bug] `MP.IsClientConnected()` does nothing

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Server#84]
It never did anything, and now still does nothing - `TClient::SetIsConnected` is never called anywhere.

**Comment by lionkor** [comment]
Should be replaced by IsSynced or similar, at least on the implementation-side.

**Comment by lionkor** [comment]
@Anonymous-275 when is UDP first sent, launcher-side?

**Comment by Anonymous-275** [comment]
When the game finished loading the map

**Comment by lionkor** [comment]
Okay, so setting this to "true" once we get UDP was correct, and intended, then

**Comment by Anonymous-275** [comment]
Yup of course

**Comment by lionkor** [comment]
Yeah this needs a complete redo, it makes no sense to do it like this - this should become part of the actual sync

**Comment by Anonymous-275** [comment]
Yeah we need to engineer a new system from top to bottom

**Comment by lionkor** [comment]
No, I mean, the IsClientConnected makes very little sense, and the assignment of a udp endpoint to a client here makes no sense either (im looking at the code). That's alright, I'll fix it for now

**Comment by Anonymous-275** [comment]
Well you kinda need to know from who is that position packet and who to send the other packs from all other clients ect...

**Comment by lionkor** [comment]
Yes :) I get that

**Comment by Anonymous-275** [comment]
It is also convenient that the first packet is when the map loaded so you know that client can even get the other's position packets in the first place

**Comment by lionkor** [comment]
I see

**Comment by Anonymous-275** [comment]
Wait what is this issue again? xD

**Comment by lionkor** [comment]
Well, this is about IsClientConnected, but I discovered the entire UDP recv loop we have is not making much sense, so I'll change it and keep the client connected the way it is (but in a new implementation)

**Comment by Anonymous-275** [comment]
Uhhhh ok... shouldn't we have a plan to execute so that the entire network system is remade according to it

**Comment by lionkor** [comment]
No, it'll behave the same :) I'm just monologing that I will change it

**Comment by Anonymous-275** [comment]
Alrighty I would say don't over do it to not waste time but you do you :)
