### ISSUE TITLE
Issue loading liblua5.3.so

### ISSUE THREAD

**Issue by Ratchet-master** [BeamMP/BeamMP-Server#89]
`
./BeamMP-Server-linux
`
`
./BeamMP-Server-linux: error while loading shared libraries: liblua5.3.so.0: cannot open shared object file: No such file or directory
`
`
ls /usr/lib64/liblua*`
`
/usr/lib64/liblua-5.1.so  /usr/lib64/liblua-5.2.so  /usr/lib64/liblua-5.3.so  /usr/lib64/libluajit-5.1.so.2  /usr/lib64/libluajit-5.1.so.2.0.4
`

Please could you advise further on how I can fix this?

Thanks

**Comment by lionkor** [comment]
@jedvod hello, please post the output of
```
uname -a
```
and 
```
lsb_release -a
```

**Comment by Ratchet-master** [comment]
Linux _-hostname-_ 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

bash: lsb_release: command not found...

**Comment by Ratchet-master** [comment]
Closing as I've read further on website that CentOS isn't officially supported, so I'll use wine.

**Comment by lionkor** [comment]
@jedvod *please* don't use wine. You can build the server from source in a few steps, for any linux distribution. See the README.md file in this repository.
