### ISSUE TITLE
[Documentation] Documentation for the MP Lua methods

### ISSUE THREAD

**Issue by justmedev** [BeamMP/BeamMP-Server#90]
**Is your feature request related to a problem? Please describe.**
When developing a Server side resource using Lua with a "smart" IDE that has autocompletion, the MP table is not documented which leads to the IDE not knowing about the methods existance.

**Possible implementations**
We could use some kind of Lua doc extension that can also document C++ code. When researching I found LDoc, a rich documentation tool that also supports documenting C-like code.

**Comment by lionkor** [comment]
This is too much work, and requires documenting the API in *yet another place*. Anyone feel free to do this and reopen the issue accordingly.

**Comment by Starystars67** [comment]
If I may @justmedev what IDE are you using as it may be possible to build an extension for it which contains the hints / snippets you may like?

**Comment by lionkor** [comment]
iirc he left the project

**Comment by justmedev** [comment]
I use Jet rains IDEs but yes, as lion noticed, I am no longer actively involved in the development of this project as I've stopped playing beamng

**Comment by Starystars67** [comment]
> iirc he left the project

Fair enough.

Even still this may be something that would be a nice QoL thing to help others in the future.
