### ISSUE TITLE
[Feature Request] Time trial Ghost cars could be possible with BeamMP's already available code

### ISSUE THREAD

**Issue by OfficialLambdax** [BeamMP/BeamMP-Server#92]
**Is your feature request related to a problem? Please describe.**
Not with a BeamMP problem. But with the lack of a feature within BeamNG thats requested for many years now by the community
e.g.
https://beamng.com/threads/race-yourself-ghost-replay-option-soon.81588/
https://www.reddit.com/r/BeamNG/comments/leld0z/having_time_trial_ghost_cars_in_beamng_would_be/

**Describe the solution you'd like**
BeamMP already has the code to recreate the driving of another player. Which is the multiplayer. In my mind it should be possible, with the already given code, to have the player able to record his own driving and then play it back. So the server would spawn the same car and apply the recorded behaviour on it, so that the player would then be able to race himself. Technically the server, client or something in between the client and server would save the packets and then reexecute them on command.

If the simplistic physics would also be enabled by the player then he wouldnt even crash into himself. Therefore we would get that ghost cars feature, which got requested by the community over the years.

**Describe alternatives you've considered**
An Alternative would be that the BeamNG devs implement that into the base game

**Additional context**
There could be a UI app, with a few buttons. Record, Stop recording, Start replay, Stop replay.
 
Its just an idea, where i think that is possible within BeamMP and that would satisfy the racing community. It definitly would satisfy me.

**Comment by OfficialLambdax** [comment]
Heres a reddit poll https://www.reddit.com/r/BeamNG/comments/tckss4/time_trail_ghost_cars_yes_or_no_that_might_be_a/

**Comment by 20dka** [comment]
I like this idea, but generally BeamMP tries to stay not bloated, and doesn't include gamemodes/minigames, instead encouraging others to create mods/plugins to achieve what they want on top of BeamMP. With that said there are a few hints already in BeamMP to help accomplish this. For example there is a `fade vehicles based on distance` feature, which, accompanied by the `simplified physics` option were meant to be used in live MP time trial/attack races

**Comment by OfficialLambdax** [comment]
The Time Trial ghost car feature will be part of my headless client
https://www.youtube.com/watch?v=ca0F-NQM1IA

**Comment by lionkor** [comment]
As this is not planned as a feature, leaving this closed. Headless client is not official as of the time of writing, so will tag this as "wont fix".
